Open project in IDE
remotion-dev/remotion pull request #1569
Opened 2022-12-14 11:24 UTC by orimdominic

This PR affects issue #1561 

I've been able to resolve this with a few caveats.

If no code editor is open, it will try to open it in VS Code by default. This happens because [guessEditor](https://github.com/remotion-dev/remotion/blob/a255b47c0daa632e4fbb49675853dff618a42788/packages/cli/src/preview-server/error-overlay/react-overlay/utils/open-in-editor.ts#L346) returns the currently open code editor and when there is none, it returns undefined

PS: I noticed that when Sublime Text is open on my computer and it should be the editor that opens up the project, I get the error in the screenshot below when I try to open the project.

![Screenshot from 2022-12-14 11-47-14](https://user-images.githubusercontent.com/37955249/207582843-98e95bac-14b5-4e62-9d30-254ccf5b3da4.png)

2022-12-15 09:30 UTC, JonnyBurger requested changes
Thanks a lot! 🙌
It works, some polishing needed.

2022-12-15 09:30 UTC, JonnyBurger commented on packages/cli/src/editor/helpers/use-menu-structure.tsx
> +					{
The action should only be displayed if `window.remotion_editorName` is not null

2022-12-15 09:30 UTC, JonnyBurger commented on packages/cli/src/editor/helpers/use-menu-structure.tsx
> +						label: 'Open in code editor...',
Can we rename it to `Open in ${window.remotion_editorName}`?
The `...` signals that a modal is opened in the Preview, so I would remove the `...`.

2022-12-15 09:30 UTC, JonnyBurger commented on packages/cli/src/editor/helpers/use-menu-structure.tsx
> +							await fetch(`/api/open-in-editor`, {
Now duplicated with the code in `OpenInEditor`, can we create a helper function to be used in both places?

2022-12-15 09:30 UTC, JonnyBurger commented on packages/cli/src/editor/helpers/use-menu-structure.tsx
> +								console.error(err)
You can handle the error with `notificationCenter.current?.addNotification()`.

2022-12-15 09:30 UTC, JonnyBurger commented on packages/cli/src/preview-server/routes.ts
> -			editor: guess[0],
Let's not default to VS Code, instead if the editor was not guessed, let's not display the menu at all.

2022-12-15 09:32 UTC, JonnyBurger commented
How do you launch Sublime normally? Should we rename `sublime_text` to `sublime`?

2022-12-15 10:13 UTC, JonnyBurger commented
Alright, thanks!
And sorry for pushing a commit to this branch, was accidentially. Will be in main soon so the diff will be clean afterwards.

2022-12-15 17:37 UTC, JonnyBurger commented
Awesome! Looks great, thanks a lot! 🙌

@MehmetAdemi Can you reward the issue?¨

2022-12-15 17:43 UTC, MehmetAdemi commented
For sure! 
Thanks @orimdominic! Can you go to issue #1561 and sign up on Algora so I can make the payment?

2022-12-15 17:51 UTC, JonnyBurger approved these changes

2022-12-15 17:57 UTC, merged

2022-12-16 00:30 UTC, orimdominic commented
> For sure @JonnyBurger ! Thanks @orimdominic! Can you go to issue #1561 and sign up on Algora so I can make the payment?

I will soonest!

2022-12-16 01:03 UTC, orimdominic commented
Felt great contributing to this!

2022-12-16 07:55 UTC, JonnyBurger commented
Awesome! Your contribution is much appreciated 🙌 💙