fix: Prevent exiting the page if there are unsaved changes to the default props
remotion-dev/remotion pull request #2745
Opened 2023-08-16 20:15 UTC by rishi-raj-jain

fix #2495
/claim #2495

2023-08-16 20:17 UTC, rishi-raj-jain commented
@JonnyBurger 

Can you give the message and duration you expect to set on this?

I added the event listener in the render modal, let me know if you think I shall shift it to somewhere else.

2023-08-17 11:51 UTC, JonnyBurger requested changes

2023-08-17 11:51 UTC, JonnyBurger commented on packages/cli/src/event-source.ts
> +					content: 'Do not save hey',
- The content could be "There are unsaved changes to the props. Do you want to leave?"
- The notification center will do nothing here, you can only prevent a page from closing if you use `window.oneforeunload`

Example:
```
window.addEventListener('beforeunload', (event) => {
  event.returnValue = 'Are you sure you want to leave?';
});
```

2023-08-17 11:51 UTC, JonnyBurger commented on packages/cli/src/editor/helpers/document-title.ts
> +declare global {
All global variables are defined in core/src/index.ts.
Can you move it there as well and update the variable name with a `remotion_` prefix?

2023-08-20 07:34 UTC, JonnyBurger commented
Thanks!

2023-08-20 07:34 UTC, JonnyBurger approved these changes

2023-08-20 07:59 UTC, merged