new-video-upload
remotion-dev/remotion pull request #537
Opened 2021-08-04 13:40 UTC by MehmetAdemi

2021-08-05 18:53 UTC, Iamshankhadeep approved these changes
LGTM

2021-08-05 18:56 UTC, Iamshankhadeep requested changes

2021-08-05 18:56 UTC, Iamshankhadeep commented on packages/docs/src/data/showcase-videos.tsx
> +        url: "<https://twitter.com/verdaccio_npm/status/1420187249145118722",
need to remove `<`

2021-08-05 18:56 UTC, Iamshankhadeep commented on packages/docs/src/data/showcase-videos.tsx
> +      url: "<https://twitter.com/_semoal>",
here need to remove `<` and `>`

2021-08-06 08:43 UTC, JonnyBurger approved these changes

2021-08-06 09:54 UTC, merged